### ISSUE TITLE
Location of clef info on line not set 

### ISSUE THREAD

**Issue by kemalkongar** [DDMAL/MEI2Volpiano#2]
The clef info location as found with the current algo is not secure. It's possible that they will not occupy spots -1 and -2 respectively.

**Comment by martha-thomae** [comment]
Yes, that is possible.

If you use libmei (or another python library for parsing xml), you could do something like this to find the `<staffDef>` element and retrieve the clef-related attributes:

**This is pymei (the python binding for libmei) code:**
```python
import pymei

staffDef_array = pymei.getElementsByName("staffDef")
staffDef1 = staffDef_array [0]
clef_shape = staffDef1.getAttribute("clef.shape")
clef_line = staffDef1.getAttribute("clef.line")
```

In this way you don't have to go line by line processing the file (you can go directly to an element) and you also don't have to depend on the position of the attributes within a particular element.

The last slide on my MEI and LibMEI presentation has some of the most useful methods to edit an MEI file using this library.

**Comment by martha-thomae** [comment]
For information on libmei and how to install the python bindings, you would need to cover these two sections of the wiki:
- [the compiling and installing of libmei](https://github.com/DDMAL/libmei/wiki/Compiling-and-Installing)
- and [the installing python bindings](https://github.com/DDMAL/libmei/wiki/Installing-the-Python-bindings)

You could use other Python xml-parsing libraries instead of libmei. They will offer similar functionalities and might be way easier to install (unfortunatelly, although libmei was designed to process MEI, it is complicated to install).

**Comment by martha-thomae** [comment]
For a Python xml-parsing library you could use the [ElementTree XML API](https://docs.python.org/3/library/xml.etree.elementtree.html#module-xml.etree.ElementTree)

You have methods `findall()`, `find()`, and `get()` that behave similar to libmei in the sense that you can access specific elements and look for their attributes (see section on [Finding interesting elements](https://docs.python.org/3/library/xml.etree.elementtree.html#finding-interesting-elements)  that uses the [example from the beginning of the page](https://docs.python.org/3/library/xml.etree.elementtree.html#parsing-xml))

**Comment by kemalkongar** [comment]
Very helpful, thank you.

**Comment by kemalkongar** [comment]
We've pushed a draft version using ElementTree, I think this issue can be closed but up to you.

**Comment by martha-thomae** [comment]
I think it can be closed too. Thank you for your work on it!

**Comment by kemalkongar** [comment]
Of course!
